/**
 * Auto-generated songs list
 * Generated on: 2026-02-25T23:52:11.560Z
 * DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate-songs-list.js instead
 */

const AVAILABLE_SONGS = [
  {
    "name": "Eurythmics - Sweet Dreams",
    "path": "Resources/Songs/Eurythmics - Sweet Dreams.mp3"
  },
  {
    "name": "I LIKE TO MOVE IT",
    "path": "Resources/Songs/I LIKE TO MOVE IT.mp3"
  },
  {
    "name": "Michael Jackson - They Don't Care About Us",
    "path": "Resources/Songs/Michael Jackson - They Don't Care About Us.mp3"
  }
];
