/**
 * Auto-generated songs list
 * Generated on: 2026-02-16T21:53:59.205Z
 * DO NOT EDIT THIS FILE MANUALLY - Run scripts/generate-songs-list.js instead
 */

const AVAILABLE_SONGS = [
  {
    "name": "Eurythmics - Sweet Dreams",
    "path": "Resources/Songs/Eurythmics - Sweet Dreams.mp3"
  },
  {
    "name": "I LIKE TO MOVE IT",
    "path": "Resources/Songs/I LIKE TO MOVE IT.mp3"
  }
];
